name: torchcfm_v2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.15=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - anndata==0.10.9
      - array-api-compat==1.9
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - catboost==1.2.7
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - clean-fid==0.1.35
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.7
      - decorator==5.1.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - forestdiffusion==1.0.6
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - grpcio==1.66.2
      - h5py==3.12.1
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.28.0
      - ipywidgets==8.1.5
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - legacy-api-wrap==1.4
      - lightgbm==4.5.0
      - lightning-bolts==0.7.0
      - lightning-utilities==0.11.7
      - llvmlite==0.43.0
      - markdown==3.7
      - markupsafe==3.0.1
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.1.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.4.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.1
      - pandas==2.0.3
      - parso==0.8.4
      - pastel==0.2.1
      - patsy==0.5.6
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - poethepoet==0.10.0
      - pot==0.9.4
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - protobuf==5.28.2
      - psutil==6.0.0
      - ptflops==0.7.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytorch-lightning==1.9.5
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - requests==2.32.3
      - scanpy==1.10.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - scprep==1.2.3
      - seaborn==0.13.2
      - session-info==1.0.0
      - six==1.16.0
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - stdlib-list==0.10.0
      - sympy==1.13.3
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tomlkit==0.13.2
      - torch==2.4.1
      - torchcde==0.2.5
      - torchcfm==1.0.6
      - torchdiffeq==0.2.4
      - torchdyn==1.0.6
      - torcheval==0.0.7
      - torchmetrics==1.4.3
      - torchsde==0.2.6
      - torchvision==0.19.1
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - trampoline==0.1.2
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - umap-learn==0.5.6
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - xgboost==2.1.1
      - yarl==1.15.2
prefix: /home/stefanofiscale/miniconda3/envs/torchcfm_v2
