model_name: 'resnet'     # Choose the network architecture to be used as feature extractor. Values: {vgg, resnet} 
optimizer: 'adam'     # Choose the optimization algorithm. Values: {adam, sgd}
num_classes: 3        # Number of output classes. 
#weight_decay: 0.0001 # Decomment when using Stochastic Gradient Descent
#momentum: 0.9        # Decomment when using Stochastic Gradient Descent
#NOTE. Experimental
learning_rate: 0.001
batch_size: 128
num_epochs: 300
