features_filename: 'features_step2_mlp/2025-08-27_resnet18_adam_80_kepler_dr25_train_features_2d_mlp_30.npy' 
#labels_filename: 'features_step1_cnn/2025-08-27_resnet18_adam_80_kepler_dr25_train_labels.npy'
output_plot_resolution: 1200