mode:         'test'         # mode = {train, test}
model_name:   'resnet18'        # Choose the network architecture to be used as feature extractor. Values: {vgg, resnet} 
#optimizer:    'adam'          # Choose the optimization algorithm. Values: {adam, sgd}
#num_classes:  3               # Number of output classes. 
#weight_decay: 0.0001          # Decomment when using Stochastic Gradient Descent
#momentum:     0.99            # Decomment when using Stochastic Gradient Descent
#learning_rate: 0.001
#batch_size:   128
#num_epochs:   50
#save_model:   True            # variabile booleana per salvataggio modello. default value: False
#purpose:      'from_scratch'     # Opzionale. Considera solo se save_model = True. values: {from_scratch, finetuned}
saved_model_name: '2025-09-29_resnet18_adam_60_kepler_dr25_balanced_from_scratch_model.pt'