dataset:
  filename_samples: 'plato_FittedEvents_phaseflux_original_multiclass_train_split_features.npy' # <light curve, id, label>
  filename_labels:  'plato_FittedEvents_phaseflux_original_multiclass_train_split_labels.npy'    # Optional    

embedding:
  algorithm:    'isomap'  # isomap, lle, mdscal, ...
  n_components: 2