# Load data from features_step1_cnn/
dataset:
  filename_samples: '2025-07-15_resnet_sgd_150_plato_flux_original_train_features.npy' # <light curve, id, label>
  filename_labels:  '2025-07-15_resnet_sgd_150_plato_flux_original_train_labels.npy'     

embedding:
  algorithm:    'isomap'      # isomap, lle, mdscal, ...
  n_components: 3
  n_neighbors:  30            # 10, 15, 30
  #radius:       Null
  eigen_solver: 'auto'
  tol:          0
  max_iter:     3000           # 200, 300, 500, 1000, 2000
  path_method:  'auto'
  neighbors_algorithm: 'auto'
  metric:       'minkowski'
  p:            3             # 1, 2, 3 
  n_jobs:       -1            # use all processors

output:
  save_features:  False 
  save_plot:      True