# Input parameters to define the network architecture of ResNet
resnet_layers_num: 34   # Number of network layers. values: 18 or 34
fc_layers_num: 1        # Number of fully-connected layers
fc_units: 512           #                           units
fc_output_size: 3       # Number of output neurons