# Input parameters to define the architecture of VGG19 
input_size:     500     # size of input data
psz:            3       # pooling size
pst:            2       #         stride
fc_layers_num:  1       # number of fully-connected layers
#fc_units:       2560    #                           units
fc_output_size: 3       # number of output neurons
