n_comp: 2         # Number of output dimensions. values={2,3}
perplexity: 50    # Larger datasets usually require a larger perplexity. Consider selecting a value between 5 and 50
max_iter: 3000
extracted_features_filename: '2025-06-21_resnet_sgd_30_tess_tey23_train_features.npy'
plot_features: True